# Generated by Django 4.1 on 2024-10-07 08:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_name_user_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.family'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alphanumeric', message='半角英数字のみ入力してください', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
