# Generated by Django 5.0.7 on 2024-10-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_child_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='family_id',
            new_name='family',
        ),
    ]
