# Generated by Django 5.0.7 on 2024-10-08 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_family_id_user_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alphanumeric', message='@で始まり、半角英数字のみ入力してください', regex='^@?[a-zA-Z0-9]+$')]),
        ),
    ]
