# Generated by Django 4.1 on 2024-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='invitation_url',
        ),
        migrations.AddField(
            model_name='family',
            name='invitations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
