# Generated by Django 4.1 on 2024-10-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcarejournal',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
